# Test your FastAPI endpoints

GET http://localhost:5001/deposit
Accept: application/json

###

POST http://localhost:5001/deposit
Accept: application/json
Content-Type: application/json

{
  "date": "25.03.2023",
  "periods": 5,
  "amount": 3000000,
  "rate": 8
}

###
